### ISSUE TITLE
Date for code upload

### ISSUE THREAD

**Issue by arvind-27** [paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries#1]
When will the repository be updated with the actual codebase for the task?

**Comment by paatrycjaa** [comment]
Hi, I think that we will upload it by the end of the year. Confirm @mpfmorawski

**Comment by mpfmorawski** [comment]
Hello @arvind-27, 
As Patrycja said, the code will definitely be uploaded befrore the end of 2023. Hopefully, it will be available earlier. We will inform you about it in this issue.

**Comment by THunderCondOR** [comment]
Hi! Any chance the code will appear soon?

**Comment by paatrycjaa** [comment]
Yes, it should appear in next few days. Sorry for the delay.

**Comment by mpfmorawski** [comment]
@arvind-27 and @THunderCondOR, the code has arrived in the repository. Thank you for your patience!
