### ISSUE TITLE
Missing .yaml Parameters

### ISSUE THREAD

**Issue by irfan112** [paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries#2]
try all .yaml files in  INPUT_CONFIG.

 PATH_DATA = 'data'
 PATH_MODELS = 'output/vlqa_POLYP_2024_05_04_17_16_50/model_final.pth'
 TRAIN = 'false'
 INPUT_CONFIG = 'output/vlqa_POLYP_2024_05_04_17_16_50/config.yaml'
  INFERENCE = 'true'
  PATH_INFERENCE_DATA = 'data/images'
  PATH_INFERENCE_TEXTS = 'data/gt.json'
  PATH_INFERENCE_OUTPUT = 'output/'
  logger.info(INPUT_CONFIG)
    
    issue : Traceback (most recent call last):
  File "C:\Users\Dell\Desktop\balil\female_client\ImageCLEF2023-MEDVQA-GI-VisionQAries\src\pipeline_vqga.py", line 44, in <module>
    TASK_TYPE = INPUT_PARAMS["model_config"]["type"]
KeyError: 'model_config'

**Comment by irfan112** [comment]
@paatrycjaa help me out please!

**Comment by mpfmorawski** [comment]
Hello @irfan112,
Thank you very much for reporting this issue. I will take care of it as soon as possible.
I hope to resolve the problem in the next few days.

**Comment by mpfmorawski** [comment]
Hello @irfan112,
Can you help me with resolving your issue?

In the details you have attached, I see that you have tried to run script `src\pipeline_vqga.py` prepared for Task 1 (VQA) with parameters related to Task 3 (VLQA). These are two different tasks with two different models and scripts.

**Which task you would like to run?**

For clarification, I have improved README.md #3 (PR will be merged into the `main` branch after review)

**Comment by mpfmorawski** [comment]
Hello @irfan112,
I got an update. PR #3 has been merged.

**Comment by mpfmorawski** [comment]
Since there has been no response for a while, I'm closing this issue. Please feel free to reopen it if you have more information to provide. Thank you!
