### ISSUE TITLE
src/template/vqg_05_dense_8k.yaml

### ISSUE THREAD

**Issue by shenbw99** [paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries#4]
Hello.
when I run script `pipeline_vqga.py` with example code
```
"python3 src/pipeline_vqga.py \
  "data/" \
  "models/" \
  "true" \
  "src/template/vqg_05_dense_8k.yaml" \
  "true" \
  "data/ImageCLEFmed-MEDVQA-GI-2023-Testing-Dataset/images/" \
  "data/inference_answers.txt" \
  "vqg_05_dense_8k.json"
```
show that  `"FileNotFoundError: [Errno 2] No such file or directory: 'src/template/vqg_05_dense_8k.yaml"` like in attach files.
I think it is caused by the lack of this `src/template/vqg_05_dense_8k.yaml` file. Can you give me this file?
Please！

![屏幕截图 2024-07-08 183942](https://github.com/paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries/assets/84695001/79d7c48a-73bd-437b-a121-09b0272048dd)

**Comment by mpfmorawski** [comment]
@shenbw99

The template has been uploaded to the repository. You can find it here: [src/template/vqg_05_dense_8k.yaml](https://github.com/paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries/blob/main/src/template/vqg_05_dense_8k.yaml)

Please let me know if you need any further assistance.

**Comment by shenbw99** [comment]
> @shenbw99
> 
> The template has been uploaded to the repository. You can find it here: [src/template/vqg_05_dense_8k.yaml](https://github.com/paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries/blob/main/src/template/vqg_05_dense_8k.yaml)
> 
> Please let me know if you need any further assistance.

Thank you so much！！！

**Comment by shenbw99** [comment]
Hello
If I want to run Task 1, do I just need to replace "type: VQG" with "type: VQA" in the "vqg_05_dense_8k.yaml" file?

**Comment by shenbw99** [comment]
Dear Maciej Morawski,

Firstly, thank you so much for your .yaml file. It is helpful for me.

Next, I would like to ask, if I want to execute the model for training
task1, can I just replace "type: VQG" in "vqg_05_dense_8k.yaml" with "type:
VQA" without modifying other parameters?

Best regards,
Bowei Shen

Maciej Morawski ***@***.***> 于2024年7月11日周四 04:48写道：

**Comment by mpfmorawski** [comment]
Hello, Bowei!

Sorry for the confusion. I see now that the example in the readme and the template we added yesterday were confusing.  For that reason, I have updated the readme here: #6 

To answer your question directly: **Yes, you need to change the value of the `type` field.**

The pipeline for both tasks was practically the same. Only the questions and answers are swapped places (for VQA the question is in the input and the answer is in the output, for VQG the answer is in the input and the question is in the output). In the source code, you can find this difference in lines [44](https://github.com/paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries/blob/main/src/pipeline_vqga.py#L44)-[48](https://github.com/paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries/blob/main/src/pipeline_vqga.py#L48) of src/pipeline_vqga.py.

We will be happy to help you if you have any more doubts!

PS: You can find more of the templates we used during the study in this commit [0ee54c](https://github.com/paatrycjaa/ImageCLEF2023-MEDVQA-GI-VisionQAries/pull/5/commits/0ee54c812357ca7a5539a516de6a37887933eba9)

**Comment by shenbw99** [comment]
Hello Maciej,

Thank you for your clarification!!!

Then,  I have a question, what format should I write the text in the file
"data/inference_answers.txt", which file for inference when "INFERENCE =
TRUE" . I checked the file "vqga_evaluation.py" and looked like it needs
the content "input_ids", "token_type_ids", "attention_mask". Is the
“input_ids” the name of the images in "
ImageCLEFmed-MEDVQA-GI-2023-Testing-Dataset"?  How should I write
"token_type_ids", "attention_mask"?

Or the file "inference_answers.txt" should be the same format as in the
training file?

I would be grateful if you could provide a sample "inference_answers.txt"
file!!!

Best regards,
Bowei Shen

Maciej Morawski ***@***.***> 于2024年7月12日周五 05:22写道：

**Comment by mpfmorawski** [comment]
Hello Bowei,
Sorry for the longer response time than before. Since this issue is already closed and you are asking for a new file, I went ahead and opened a new GitHub Issue: #7 . I would appreciate it if we could continue the discussion about this issue in the newly opened issue #7 .

**Comment by shenbw99** [comment]
Hello Maciej,

Thank you very much for your patience in responding my questions and
requests.
I have successfully demonstrated the model's functionality using the
"inference_single_text" function in the "vqga_evaluation.py" file.
Your code is very helpful to me, thank you again!!!

Best regards,
Bowei Shen

Maciej Morawski ***@***.***> 于2024年7月18日周四 15:02写道：
